### ISSUE TITLE
Cannot install it on Ubuntu 16.04.

### ISSUE THREAD

**Issue by eliassotodo** [tcr/mediakeys#5]
Can't install it using `npm install`

> dbus@0.2.19 install /home/brahiansoto_me/Projects/harmony/node_modules/dbus
> node-gyp configure build

Package expat was not found in the pkg-config search path.
Perhaps you should add the directory containing `expat.pc'
to the PKG_CONFIG_PATH environment variable
No package 'expat' found
gyp: Call to 'pkg-config  --libs-only-l --libs-only-other expat' returned exit status 1 while in binding.gyp. while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error:`gyp`failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:305:16)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Linux 4.4.0-38-generic
gyp ERR! command "/usr/bin/nodejs" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "configure" "build"
gyp ERR! cwd /home/brahiansoto_me/Projects/harmony/node_modules/dbus
gyp ERR! node -v v6.7.0
gyp ERR! node-gyp -v v3.3.1
gyp ERR! not ok 
npm WARN install:dbus@0.2.19 dbus@0.2.19 install:`node-gyp configure build`
npm WARN install:dbus@0.2.19 Exit status 1

> mediakeys@0.1.1 install /home/brahiansoto_me/Projects/harmony/node_modules/mediakeys
> node-gyp rebuild

Package expat was not found in the pkg-config search path.
Perhaps you should add the directory containing `expat.pc'
to the PKG_CONFIG_PATH environment variable
No package 'expat' found
gyp: Call to 'pkg-config  --libs-only-l --libs-only-other expat' returned exit status 1 while in dbus/binding.gyp. while loading dependencies of binding.gyp while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error:`gyp`failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:305:16)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Linux 4.4.0-38-generic
gyp ERR! command "/usr/bin/nodejs" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/brahiansoto_me/Projects/harmony/node_modules/mediakeys
gyp ERR! node -v v6.7.0
gyp ERR! node-gyp -v v3.3.1
gyp ERR! not ok 
npm WARN install:mediakeys@0.1.1 mediakeys@0.1.1 install:`node-gyp rebuild`
npm WARN install:mediakeys@0.1.1 Exit status 1

**Comment by JakeStanger** [comment]
This is still the case and I've been unable to find a fix for it. Anybody know what's going on or got a fix for it?

**Comment by stefanomartinengo** [comment]
I'm also running into this issue still
